name: Ritual de CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configura Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Instala dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Executa testes
      run: |
        pytest
