name: Ritual de CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Testa Sintaxe Bash
      run: |
        for script in src/*.sh; do
          bash -n "$script" || echo "Erro em $script"
        done
