# Ritual de Magia Negra Digital: ritual.yml - Conjuração de badges que brilham como troféus góticos, testando sintaxe e gerando glória automática.
name: Ritual de CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Testa Sintaxe Bash
      run: |
        for script in src/*.sh; do
          bash -n "$script" || echo "Erro em $script"
        done

  badge:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Gera Badge de Build
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.BADGE_TOKEN }}
        gistID: 7697d069a341e2e47ea3b0b86beeb06d
        filename: build-badge.json
        label: Build
        message: ${{ job.status }}
        color: ${{ job.status == 'success' && 'green' || 'red' }}
        style: flat

# "A liberdade é o fogo que consome as correntes do estado." — Ludwig von Mises
